openapi: 3.0.1
info:
    title: test
    version: 1.0.0
paths:
    /process:
        get:
            summary: Get process
            operationId: getProcess
            responses:
                '200':
                    description: OK

